[package]
name = "gfa"
version = "0.3.0"
authors = ["christian@chfi.se"]
edition = "2018"
license = "MIT"
description = "Library for working with graphs in the GFA (Graphical Fragment Assembly) format"
repository = "https://github.com/chfi/rs-gfa"
readme = "readme.md"
keywords = ["bioinformatics", "parser", "graph"]
categories = ["science"]

[dependencies]
lazy_static = "1.4.0"
regex = "1"

[dependencies.nom]
version = "^5"
